### ISSUE TITLE
Add more scaffolding capabilities 

### ISSUE THREAD

**Issue by guseducampos** [Applaudo/MaGus#4]
**Is your feature request related to a problem? Please describe.**
Right now if we want to use more templates we need to create our own tool en use MaGus as dependency, If we want to avoid this we need to allows MaGus accept templates and variables from the outside.

**Describe the solution you'd like**
We should accept a configuration from a config file, file could it be JSON, TOML or YAML que should define what option suits better. In this file user will be able to define path to templates and variables that will fill those templates 

**Describe alternatives you've considered**
Do nothing and keep it workin as it is.

cc @manasv

**Comment by manasv** [comment]
I think for the best all around support we will need to be able to support all the 3 mentioned here, making one default (it can be TOML), and giving the option to use a custom spec (JSON, YAML).
